<?php

namespace Database\Seeders;

use App\Models\Laporan;
use Illuminate\Database\Seeder;

class LaporanSeeder extends Seeder
{
    public function run(): void
    {
        $laporans = [
            [
                'kode_laporan' => 'IRG-2026-00001',
                'user_id' => 1,
                'nama_pelapor' => 'Budi Santoso',
                'telepon' => '081234567890',
                'email' => 'budi@email.com',
                'status_pelapor' => 'petani',
                'nama_saluran' => 'Saluran Primer Utara',
                'jenis_saluran' => 'primer',
                'kecamatan' => 'Krian',
                'desa' => 'Sukajaya',
                'alamat' => 'Jl. Raya Krian KM 5',
                'deskripsi_lokasi' => 'Di sebelah timur pasar Krian, dekat jembatan merah',
                'jenis_kerusakan' => 'Bocor besar pada saluran primer sepanjang 3 meter di dekat jembatan. Air keluar cukup deras dan menggenangi jalan setapak.',
                'tingkat_keparahan' => 'berat',
                'dampak_pertanian' => 'sedang',
                'lama_kerusakan' => '1-7',
                'deskripsi_kerusakan' => 'Air merembes ke sawah sekitar dan mengurangi debit aliran ke hilir. Lahan pertanian seluas ±2 ha terancam kekurangan air.',
                'latitude' => -7.4480,
                'longitude' => 112.7180,
                'status' => 'diverifikasi',
                'catatan_verifikasi' => 'Laporan valid, tim akan mengecek lokasi.',
                'tanggal_verifikasi' => now()->subDays(5),
            ],
            [
                'kode_laporan' => 'IRG-2026-00002',
                'user_id' => 2,
                'nama_pelapor' => 'Siti Aminah',
                'telepon' => '081234567891',
                'email' => 'siti@email.com',
                'status_pelapor' => 'petani',
                'nama_saluran' => 'Saluran Sekunder Timur',
                'jenis_saluran' => 'sekunder',
                'kecamatan' => 'Porong',
                'desa' => 'Mekarjaya',
                'alamat' => 'Jl. Porong Lama',
                'deskripsi_lokasi' => 'Di belakang sekolah SD Mekarjaya',
                'jenis_kerusakan' => 'Longsor pada tebing saluran sekunder sepanjang 5 meter. Material tanah menutup sebagian saluran.',
                'tingkat_keparahan' => 'sedang',
                'dampak_pertanian' => 'ringan',
                'lama_kerusakan' => 'baru',
                'deskripsi_kerusakan' => 'Aliran air terhambat sehingga beberapa petak sawah kehilangan supply air. Perlu pembersihan material longsor.',
                'latitude' => -7.4650,
                'longitude' => 112.7350,
                'status' => 'diproses',
                'catatan_verifikasi' => 'Valid, perlu penanganan segera.',
                'tanggal_verifikasi' => now()->subDays(4),
                'tanggal_proses' => now()->subDays(3),
            ],
            [
                'kode_laporan' => 'IRG-2026-00003',
                'user_id' => 3,
                'nama_pelapor' => 'Ahmad Rizki',
                'telepon' => '081234567892',
                'email' => 'ahmad@email.com',
                'status_pelapor' => 'masyarakat',
                'nama_saluran' => 'Saluran Tersier Barat',
                'jenis_saluran' => 'tersier',
                'kecamatan' => 'Buduran',
                'desa' => 'Cangkuang',
                'alamat' => 'Dusun Cangkuang Wetan',
                'deskripsi_lokasi' => '200 meter dari pertigaan Cangkuang',
                'jenis_kerusakan' => 'Sedimentasi berat pada saluran tersier. Kedalaman air hanya 20 cm dari normal 80 cm.',
                'tingkat_keparahan' => 'ringan',
                'dampak_pertanian' => 'ringan',
                'lama_kerusakan' => '7-30',
                'deskripsi_kerusakan' => 'Aliran air sangat terhambat. Beberapa lahan sawah mulai kering.',
                'latitude' => -7.4300,
                'longitude' => 112.7050,
                'status' => 'selesai',
                'catatan_verifikasi' => 'Valid, sedimentasi mengganggu aliran.',
                'tanggal_verifikasi' => now()->subDays(10),
                'tanggal_proses' => now()->subDays(9),
                'tanggal_selesai' => now()->subDays(7),
            ],
            [
                'kode_laporan' => 'IRG-2026-00004',
                'user_id' => null,
                'nama_pelapor' => 'Dewi Lestari',
                'telepon' => '081234567893',
                'email' => null,
                'status_pelapor' => 'masyarakat',
                'nama_saluran' => 'Jembatan Irigasi Utara',
                'jenis_saluran' => 'primer',
                'kecamatan' => 'Gedangan',
                'desa' => 'Gedangan',
                'alamat' => 'Jl. Raya Gedangan',
                'deskripsi_lokasi' => 'Di sebelah utara pasar Gedangan',
                'jenis_kerusakan' => 'Retak pada struktur jembatan irigasi. Besi tulangan terlihat pada beberapa bagian.',
                'tingkat_keparahan' => 'kritis',
                'dampak_pertanian' => 'berat',
                'lama_kerusakan' => '1-7',
                'deskripsi_kerusakan' => 'Beban kendaraan berpotensi memperparah kerusakan. Perlu penanganan segera.',
                'latitude' => -7.4250,
                'longitude' => 112.6950,
                'status' => 'menunggu',
            ],
            [
                'kode_laporan' => 'IRG-2026-00005',
                'user_id' => null,
                'nama_pelapor' => 'Rudi Hartono',
                'telepon' => '081234567894',
                'email' => null,
                'status_pelapor' => 'petani',
                'nama_saluran' => 'Saluran Tersier Selatan',
                'jenis_saluran' => 'tersier',
                'kecamatan' => 'Tanggulangin',
                'desa' => 'Tanggulangin',
                'alamat' => 'Dusun Selatan',
                'deskripsi_lokasi' => 'Di dekat mushola Al-Hidayah',
                'jenis_kerusakan' => 'Saluran tersier tersumbat sampah plastik dan dedaunan. Aliran air terhambat total.',
                'tingkat_keparahan' => 'sedang',
                'dampak_pertanian' => 'sedang',
                'lama_kerusakan' => 'baru',
                'deskripsi_kerusakan' => 'Sawah kekurangan air. Perlu pembersihan segera.',
                'latitude' => -7.4400,
                'longitude' => 112.7100,
                'status' => 'ditolak',
                'catatan_verifikasi' => 'Laporan duplikat dengan laporan sebelumnya.',
            ],
        ];

        foreach ($laporans as $laporan) {
            Laporan::create($laporan);
        }
    }
}
