<?php

namespace Database\Seeders;

use App\Models\Saluran;
use Illuminate\Database\Seeder;

class SaluranSeeder extends Seeder
{
    public function run(): void
    {
        $salurans = [
            [
                'nama' => 'Saluran Primer Krian Barat',
                'jenis' => 'primer',
                'kecamatan' => 'Krian',
                'desa' => 'Krian',
                'alamat' => 'Jl. Raya Krian',
                'deskripsi' => 'Saluran primer utama yang mensuplai air ke seluruh wilayah irigasi Krian. Kondisi prima, kapasitas penuh. Struktur beton tidak ada keretakan.',
                'kondisi' => 'baik',
                'latitude' => -7.4478,
                'longitude' => 112.7183,
                'level_air' => '2.1 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Sal. Sekunder Tambak Rejo',
                'jenis' => 'sekunder',
                'kecamatan' => 'Krian',
                'desa' => 'Tambak Rejo',
                'alamat' => 'Desa Tambak Rejo',
                'deskripsi' => 'Sedimentasi lumpur cukup tebal di beberapa titik. Perlu pengerukan untuk mengembalikan kapasitas saluran.',
                'kondisi' => 'perbaikan',
                'latitude' => -7.4350,
                'longitude' => 112.7000,
                'level_air' => '0.5 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Saluran Tersier Junwatu',
                'jenis' => 'tersier',
                'kecamatan' => 'Krian',
                'desa' => 'Junwatu',
                'alamat' => 'Desa Junwatu',
                'deskripsi' => 'Kerusakan ringan pada dinding saluran sepanjang 3 meter. Dapat ditangani dengan perbaikan mandiri.',
                'kondisi' => 'rusak-ringan',
                'latitude' => -7.4520,
                'longitude' => 112.7200,
                'level_air' => '0.2 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Pintu Air Krian Indah',
                'jenis' => 'pintu',
                'kecamatan' => 'Krian',
                'desa' => 'Krian',
                'alamat' => 'Jl. Krian Indah No.45',
                'deskripsi' => 'Pintu air pengatur aliran ke saluran sekunder. Mekanisme pembukaan berfungsi normal.',
                'kondisi' => 'baik',
                'latitude' => -7.4480,
                'longitude' => 112.7190,
                'level_air' => 'Buka 75%',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Sal. Primer Sidoarjo Kota',
                'jenis' => 'primer',
                'kecamatan' => 'Sidoarjo',
                'desa' => 'Sidoarjo',
                'alamat' => 'Jl. Diponegoro No.40',
                'deskripsi' => 'Saluran primer yang mengairi area pertanian di sekitar pusat kota Sidoarjo. Kondisi terawat dengan baik.',
                'kondisi' => 'baik',
                'latitude' => -7.4475,
                'longitude' => 112.7150,
                'level_air' => '1.8 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Saluran Sekunder Porong',
                'jenis' => 'sekunder',
                'kecamatan' => 'Porong',
                'desa' => 'Porong',
                'alamat' => 'Jl. Ahmad Yani No.55',
                'deskripsi' => 'Debit air meningkat drastis akibat hujan deras. Terdapat retak pada dinding saluran sepanjang 15 meter. Perlu penanganan segera.',
                'kondisi' => 'rusak-berat',
                'latitude' => -7.4650,
                'longitude' => 112.7350,
                'level_air' => '0.1 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Sal. Tersier Tanggulangin',
                'jenis' => 'tersier',
                'kecamatan' => 'Tanggulangin',
                'desa' => 'Tanggulangin',
                'alamat' => 'Desa Tanggulangin',
                'deskripsi' => 'Terdapat kerusakan ringan pada bagian dasar saluran. Sedang dalam proses perbaikan oleh petugas lapangan.',
                'kondisi' => 'perbaikan',
                'latitude' => -7.4400,
                'longitude' => 112.7100,
                'level_air' => '0.3 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Bendungan Kloposeping',
                'jenis' => 'bendungan',
                'kecamatan' => 'Krian',
                'desa' => 'Kloposeping',
                'alamat' => 'Desa Kloposeping',
                'deskripsi' => 'Bendungan penampung air utama untuk wilayah irigasi Krian. Kapasitas tampung masih optimal.',
                'kondisi' => 'baik',
                'latitude' => -7.4550,
                'longitude' => 112.7250,
                'level_air' => 'Penuh 85%',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Saluran Sekunder Buduran',
                'jenis' => 'sekunder',
                'kecamatan' => 'Buduran',
                'desa' => 'Buduran',
                'alamat' => 'Desa Buduran',
                'deskripsi' => 'Saluran sekunder yang melayani area persawahan Buduran. Kondisi bersih, tidak ada hambatan.',
                'kondisi' => 'baik',
                'latitude' => -7.4300,
                'longitude' => 112.7050,
                'level_air' => '0.8 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Saluran Tersier Gedangan',
                'jenis' => 'tersier',
                'kecamatan' => 'Gedangan',
                'desa' => 'Gedangan',
                'alamat' => 'Desa Gedangan',
                'deskripsi' => 'Kerusakan sedang pada fondasi saluran. Ada bagian yang bocor dan perlu re-grouting.',
                'kondisi' => 'rusak-sedang',
                'latitude' => -7.4250,
                'longitude' => 112.6950,
                'level_air' => '0.15 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Pintu Air Wonoayu',
                'jenis' => 'pintu',
                'kecamatan' => 'Wonoayu',
                'desa' => 'Wonoayu',
                'alamat' => 'Desa Wonoayu',
                'deskripsi' => 'Pintu air pengatur ke saluran tersier Wonoayu. Kondisi baik, sedikit karat pada engsel.',
                'kondisi' => 'baik',
                'latitude' => -7.4420,
                'longitude' => 112.7220,
                'level_air' => 'Buka 30%',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Sal. Sekunder Porong Lama',
                'jenis' => 'sekunder',
                'kecamatan' => 'Porong',
                'desa' => 'Porong',
                'alamat' => 'Jl. Porong Lama',
                'deskripsi' => 'Terdapat penyumbatan pada beberapa titik akibat sampah. Petugas sedang melakukan pembersihan.',
                'kondisi' => 'rusak-sedang',
                'latitude' => -7.4600,
                'longitude' => 112.7300,
                'level_air' => '0.4 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Saluran Primer Waru',
                'jenis' => 'primer',
                'kecamatan' => 'Waru',
                'desa' => 'Waru',
                'alamat' => 'Desa Waru',
                'deskripsi' => 'Saluran primer utama wilayah Waru. Kapasitas optimal, tidak ada kendala.',
                'kondisi' => 'baik',
                'latitude' => -7.3400,
                'longitude' => 112.7300,
                'level_air' => '2.5 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Sal. Tersier Taman',
                'jenis' => 'tersier',
                'kecamatan' => 'Sidoarjo',
                'desa' => 'Taman',
                'alamat' => 'Desa Taman',
                'deskripsi' => 'Beberapa titik ada keretakan kecil pada dinding saluran. Perlu plester ulang.',
                'kondisi' => 'rusak-ringan',
                'latitude' => -7.4500,
                'longitude' => 112.7100,
                'level_air' => '0.2 m3/s',
                'status' => 'aktif',
            ],
            [
                'nama' => 'Pintu Air Sidokare',
                'jenis' => 'pintu',
                'kecamatan' => 'Krian',
                'desa' => 'Sidokare',
                'alamat' => 'Jl. Sidokare',
                'deskripsi' => 'Pintu air utama pengendali distribusi air irigasi ke wilayah Krian Barat. Kondisi struktur baik.',
                'kondisi' => 'baik',
                'latitude' => -7.4520,
                'longitude' => 112.7200,
                'level_air' => 'Buka 50%',
                'status' => 'aktif',
            ],
        ];

        foreach ($salurans as $saluran) {
            Saluran::create($saluran);
        }
    }
}
